### ISSUE TITLE
Huawei cloud Moodle error downloading Moodle-LMS

### ISSUE THREAD

**Issue by tangi07** [Websoft9/ansible-moodle#11]
**Describe the bug**
```
TASK [moodle : Download Moodle-LMS] *****************************************************************
fatal: [159.138.157.59]: FAILED! => {"changed": false, "msg": "Failure downloading https://download.moodle.org/stable311/moodle-3.11.6.zip, HTTP Error 403: Forbidden"}
```
## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [x] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [x] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
[华为云已经提工单](https://console.huaweicloud.com/ticket/?agencyId=0927fbe6678025b31f7ec0188f305768&region=ap-southeast-1&locale=zh-cn#/ticketindex/smartTickets?incidentId=TS202203170615)

```
您好，如刚才电话和您沟通：
1.eip购买的时候是随机分配的；
2.这边使用香港的测试机，用跟您119同网段的eip去wget https://download.moodle.org/stable311/moodle-3.11.6.zip 的时候提示403，把eip更换成94网段后就可以正常访问，见上图；
3.用绑定94段eip的机器和您的机器做tracepath测试，路径都是一样的；
综上，怀疑是对端对119网段的eip有拦截，因为119网段是新扩容的网段，当前ipv4地址都是重复使用的，119网段以前可能是在其他地区使用，如果对端做地址校验的数据库没及时更新，会导致校验不准确，进一步影响访问，谢谢您！
```

**Comment by chendelin1982** [comment]
Use docker image to replace this role
